server:
  port: ${SERVER_PORT:12000}

spring:
  application:
    name: identity-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  datasource:
    url: jdbc:oracle:thin:@${ORACLE_DB_HOST:localhost}:${ORACLE_DB_PORT:13000}/${ORACLE_DB_NAME:IDENTITY_DB}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${IDENTITY_DB_USER:user}
    password: ${IDENTITY_DB_USER_PASSWORD:password}

rabbitmq:
  exchange-name: user-exchange
  verification-code-routing-key: verification-code-event
  reset-password-code-routing-key: reset-password-code-event


application:
  admin:
    email: ${ERECEPTA_ADMIN_EMAIL}
    password: ${ERECEPTA_ADMIN_PASSWORD}
    phone: ${ERECEPTA_ADMIN_PHONE}
    first-name: ${ERECEPTA_ADMIN_FIRST_NAME}
    last-name: ${ERECEPTA_ADMIN_LAST_NAME}
    date-of-birth: ${ERECEPTA_ADMIN_DATE_OF_BIRTH}
    pesel: ${ERECEPTA_ADMIN_PESEL}
    gender: ${ERECEPTA_ADMIN_GENDER}

  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION:1h}
      refresh-expiration: ${APPLICATION_SECURITY_REFRESH_EXPIRATION:7d}

  codes:
    expiration: ${APPLICATION_ACTION_TOKEN_EXPIRATION:15m}
    length: 6

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${ERECEPTA_EUREKA_HOST:localhost}:${ERECEPTA_EUREKA_PORT:8761}/eureka