spring:
  application:
    name: medical-documents-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  grpc:
    client:
      channels:
        user:
          address: ${ERECEPTA_USER_CHANNEL:0.0.0.0:9090}
        medication:
          address: ${ERECEPTA_MEDICATION_CHANNEL:0.0.0.0:9090}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${ERECEPTA_EUREKA_HOST:localhost}:${ERECEPTA_EUREKA_PORT:8761}/eureka

rabbitmq:
  exchange-name: prescription-exchange
  generate-prescription-event-routing-key: generate-prescription-event

server:
  port: ${PATIENT_RECORD_SERVICE_INTERNAL_PORT:12005}