server:
  port: ${ADMIN_SERVICE_INTERNAL_PORT:15000}

spring:
  application:
    name: admin-service
  grpc:
    client:
      channels:
        user:
          address: '${ERECEPTA_USER_CHANNEL:identity-service:9090}'
        visit:
          address: '${ERECEPTA_VISIT_CHANNEL:visit-service:9090}'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${ERECEPTA_EUREKA_HOST:localhost}:${ERECEPTA_EUREKA_PORT:8761}/eureka