spring:
  grpc:
    client:
      channels:
        user:
          address: ${ERECEPTA_USER_CHANNEL:0.0.0.0:9090}
        medication:
          address: ${ERECEPTA_MEDICATION_CHANNEL:0.0.0.0:9090}
  application:
    name: patient-record-service
  datasource:
    url: jdbc:postgresql://postgres:5432/patient_record_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${ERECEPTA_EUREKA_HOST:localhost}:${ERECEPTA_EUREKA_PORT:8761}/eureka

server:
  port: ${PATIENT_RECORD_SERVICE_INTERNAL_PORT:14000}
