server:
  port: ${SERVER_PORT:12002}

spring:
  application:
    name: mediation-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: admin
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect